### ISSUE TITLE
Custom image not shown

### ISSUE THREAD

**Issue by Metis77** [heimrichhannot/contao-youtube#5]
If selecting a custom image, this wont show up:
<img width="314" alt="bildschirmfoto 2018-04-18 um 22 00 49" src="https://user-images.githubusercontent.com/1408361/38955465-0f86e214-4355-11e8-9fc3-d9d36bc07c22.png">

Tested in Contao 4.4.17 & 4.4.18.

**Comment by fatcrobat** [comment]
Have u entered a custom youtubeApiKey in contao system settings?

**Comment by Metis77** [comment]
I have to confess, that I do not remember.
But if this was necessary in the settings, I probably did so.

By now I solved it differently, so I can sorrily not check it.

**Comment by GMTeams** [comment]
Sorry for opening this again, but I have the same problem.

I have added a youtube API key in the contao settings (do you know how I can check if the key is working?).

And I have added a custom thumbnail, but the _img src_ is "unknown". Tested in all templates. I also cleared the contao scriptcache.

Apart from this - shouldn't work a custom image without a API key? I thought the API key is oly necessary for getting images directly from youtube. In contao filemanager I see images with "0,0kb" - I think that is because I didn't had a key before.

Thank you very much!
